### ISSUE TITLE
Forge: java.base does not export sun.security.util on clean install

### ISSUE THREAD

**Issue by Jummit** [architectury/architectury-example-mod#8]
I get this error on the forge launch on a clean install:

```
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x71a794e5) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x71a794e5
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:105)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
        at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:333)
```

It seems that this is a known problem:

> OroArmor:
> Forge doesn't work
> ...
> Shedaniel is working on it
> But they're busy

**Comment by shedaniel** [comment]
This is caused by using J16 with 1.16 Forge, which is not fixed in 0.7.2-4, use J15 or below or wait until I port this example mod to 0.10.0 loom
